### ISSUE TITLE
Jail

### ISSUE THREAD

**Issue by ConfusedAlex** [TheBloodyUnicorns/SMP-Configs#10]
```
#If true attacking players who die on enemy-town land will be placed into the defending town's jail if it exists.
  #Requires town_respawn to be true in order to work.
  is_jailing_attacking_enemies: 'false'

  #If true attacking players who are considered an outlaw, that are killed inside town land will be placed into the defending town's jail if it exists.
  #Requires town_respawn to be true in order to work.
  is_jailing_attacking_outlaws: 'false'

  #How many hours an attacking outlaw will be jailed for.
  outlaw_jail_hours: '1'

  #If true jailed players can use items that teleport, ie: Ender Pearls & Chorus Fruit, but are still barred from using other methods of teleporting.
  jail_allows_teleport_items: 'false'

  #If false jailed players can use /town leave, and escape a jail.
  jail_denies_town_leave: 'false'

  bail:

    #If true players can pay a bail amount to be unjailed.
    is_allowing_bail: 'false'

    #Amount that bail costs for normal residents/nomads.
    bail_amount: '10'

    #Amount that bail costs for Town mayors.
    bail_amount_mayor: '10'

    #Amount that bail costs for Nation kings.
    bail_amount_king: '10'


```
