### ISSUE TITLE
Towny Levels runterskalieren

### ISSUE THREAD

**Issue by confusedalex** [TheBloodyUnicorns/SMP-Configs#6]
Vorschlag Town und Nation Levels down zu scalen, da nicht genug Spieler erwartet werden um so viele Level zu rechtfertigen.

Auszug aus der Config:
```
levels:
  # default Town levels.
  town_level:
  - numResidents: 0
    debtCapModifier: 1.0
    namePostfix: ' Ruine'
    mayorPrefix: 'Spirit '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 1
    upkeepModifier: 1.0
    townOutpostLimit: 0
  - numResidents: 1
    debtCapModifier: 1.0
    namePostfix: ' (Siedlung)'
    mayorPrefix: 'Hermit '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 16
    upkeepModifier: 1.0
    townOutpostLimit: 0
  - numResidents: 2
    debtCapModifier: 1.0
    namePostfix: ' (Kleines Dorf)'
    mayorPrefix: 'Chief '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 32
    upkeepModifier: 1.0
    townOutpostLimit: 1
  - numResidents: 6
    debtCapModifier: 1.0
    namePostfix: ' (Dorf)'
    mayorPrefix: 'Baron Von '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 96
    upkeepModifier: 1.0
    townOutpostLimit: 1
  - numResidents: 10
    debtCapModifier: 1.0
    namePostfix: ' (Kleinstadt)'
    mayorPrefix: 'Viscount '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 160
    upkeepModifier: 1.0
    townOutpostLimit: 2
  - numResidents: 14
    debtCapModifier: 1.0
    namePostfix: ' (Stadt)'
    mayorPrefix: 'Count Von '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 224
    upkeepModifier: 1.0
    townOutpostLimit: 2
  - numResidents: 20
    debtCapModifier: 1.0
    namePostfix: ' (Großstadt)'
    mayorPrefix: 'Earl '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 320
    upkeepModifier: 1.0
    townOutpostLimit: 3
  - numResidents: 24
    debtCapModifier: 1.0
    namePostfix: ' (Metropole)'
    mayorPrefix: 'Duke '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 384
    upkeepModifier: 1.0
    townOutpostLimit: 3
  # default Nation levels.
  nation_level:
  - kingPostfix: ''
    capitalPostfix: ''
    upkeepModifier: 1.0
    kingPrefix: 'Anführer '
    capitalPrefix: ''
    numResidents: 0
    nationBonusOutpostLimit: 0
    namePostfix: ' (Staat)'
    townBlockLimitBonus: 10
    namePrefix: 'Land von '
    nationZonesSize: 1
    nationTownUpkeepModifier: 1.0
  - kingPostfix: ''
    capitalPostfix: ''
    upkeepModifier: 1.0
    kingPrefix: 'Graf '
    capitalPrefix: ''
    numResidents: 10
    nationBonusOutpostLimit: 1
    namePostfix: ' (Staat)'
    townBlockLimitBonus: 20
    namePrefix: 'Föderation von '
    nationZonesSize: 1
    nationTownUpkeepModifier: 1.0
  - kingPostfix: ''
    capitalPostfix: ''
    upkeepModifier: 1.0
    kingPrefix: 'Herzog '
    capitalPrefix: ''
    numResidents: 20
    nationBonusOutpostLimit: 2
    namePostfix: ' (Staat)'
    townBlockLimitBonus: 40
    namePrefix: 'Herzogtum '
    nationZonesSize: 1
    nationTownUpkeepModifier: 1.0
  - kingPostfix: ''
    capitalPostfix: ''
    upkeepModifier: 1.0
    kingPrefix: 'König '
    capitalPrefix: ''
    numResidents: 30
    nationBonusOutpostLimit: 3
    namePostfix: ' (Staat)'
    townBlockLimitBonus: 60
    namePrefix: 'Königreich '
    nationZonesSize: 2
    nationTownUpkeepModifier: 1.0
  - kingPostfix: ''
    capitalPostfix: ''
    upkeepModifier: 1.0
    kingPrefix: 'Imperator '
    capitalPrefix: ''
    numResidents: 40
    nationBonusOutpostLimit: 4
    namePostfix: ' Imperium'
    townBlockLimitBonus: 100
    namePrefix: 'Das '
    nationZonesSize: 2
    nationTownUpkeepModifier: 1.0
```
