### ISSUE TITLE
Health regernation in Städten?

### ISSUE THREAD

**Issue by confusedalex** [TheBloodyUnicorns/SMP-Configs#8]
```
  # Players within their town or allied towns will regenerate half a heart after every health_regen_speed seconds.
  health_regen:
    speed: 3s
    enable: 'true'
```
